# Generated by Django 4.2.27 on 2026-04-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Service image (recommended: 400x300px)', null=True, upload_to='services/'),
        ),
    ]
