# Generated by Django 4.2.27 on 2026-06-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='is_accepting_bookings',
            field=models.BooleanField(default=False, help_text='Enable this to allow clients to book appointments with this counselor'),
        ),
    ]
